### ISSUE TITLE
Add dotnet jb inspectcode

### ISSUE THREAD

**Issue by JamieJamesJamie** [JamieJamesJamie/Advent-of-Code-Dotnet#12]
Setup of this (potentially global) dotnet tool:

```json
    "jetbrains.resharper.globaltools": {
      "version": "2023.2.2",
      "commands": [
        "jb"
      ]
    }
```

Something like this is a potential GitHub action:

```yaml
  resharper-globaltools:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.401"
      - run: |
          dotnet tool restore
          dotnet jb inspectcode --build -f='sarif' -o='report.sarif' AdventOfCode.sln
      - Replace the below with this:
          https://github.com/marketplace/actions/qodana-scan
      - name: Post SARIF findings in the pull request
        if: github.event_name == 'pull_request'
        uses: sett-and-hive/sarif-to-comment-action@v2.0.1
        with:
          sarif-file: report.sarif
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: ${{ github.head_ref }}
          pr-number: ${{ github.event.number }}
```

You could also setup a pre-commit hook in dotnet husky:

```json
      {
         "name": "Run JB Clean Up Code",
         "command": "cmd",
         "pathMode": "relative",
         "args": [
           "/c",
           "dotnet",
           "jb",
           "cleanupcode",
           "proj.sln",
           "--profile=Team: Full Cleanup",
           "--include=${args}"
         ],
         "group": "pre-commit"
      }
```
