### ISSUE TITLE
Reference .nvmrc for node version

### ISSUE THREAD

**Issue by JamieJamesJamie** [JamieJamesJamie/Advent-of-Code-Dotnet#27]
https://github.com/renovatebot/renovate/issues/7716#issuecomment-1679833740

actions/setup-node supports nvm directly now, which makes this super easy:

```yml
- uses: actions/setup-node@v3
  with:
    node-version-file: '.nvmrc'
```

_Originally posted by @noahtallen in https://github.com/renovatebot/renovate/issues/7716#issuecomment-1679833740_
